### ISSUE TITLE
Moving a polygon doesn't work

### ISSUE THREAD

**Issue by yckart** [jriecken/sat-js#1]
I try to move and draw a polygon, but don't get it to work.

http://fiddle.jshell.net/HLHa8/

Any ideas?

**Comment by goldenratio** [comment]
sorry to bump this up.
When I setAngle(), polygon doesn't rotate from origin. Probably I am missing something. Can you please help?
http://fiddle.jshell.net/c7dofx28/

**Comment by goldenratio** [comment]
sorry. nevermind guys..
http://fiddle.jshell.net/e15w01bz/2/
