### ISSUE TITLE
Wrong calculation of a polygon inside an another one

### ISSUE THREAD

**Issue by Patrick-RUTKA** [jriecken/sat-js#28]
Hi,

I have a problem with the collision of a box with another polygon

Here is an example of it : http://jsfiddle.net/oxc5f428/5/

When my mouse gets inside the bounding-box, the response['aInB'] is "true" and even when my mouse is on the top-left position, I still get "true"

Could you fix this please ?

**Comment by Patrick-RUTKA** [comment]
Sorry, it's a convexe polygon.

**Comment by jriecken** [comment]
Yeah, the Separating Axis Theorem only works for convex polygons, not concave ones. You can usually models a concave polygon as a set of smaller convex ones though.
