### ISSUE TITLE
sat.d.ts

### ISSUE THREAD

**Issue by Tiramisusie** [jriecken/sat-js#30]
Your project is great! But it will be much better if you can provide a sat.d.ts file, which i can use in my Typescript project.

**Comment by jriecken** [comment]
It seems like http://definitelytyped.org/ (https://github.com/borisyankov/DefinitelyTyped) would be a better place for a `sat.d.ts`. Unfortunately I don't use Typescript and so do not know enough to create the definition myself.

I'm sure a Pull Request to DefinitelyTyped would be accepted though!
