### ISSUE TITLE
Polygon-circle test problem [Resolved]

### ISSUE THREAD

**Issue by ppisecky** [jriecken/sat-js#33]
I am trying to test a polygon against a circle, but I cannot get it to work. Sorry for posting as issue, but I don't know where else to ask. This seems like a great library with a lot of work put into it so I would love to give it shot, but cannot seeem to get it working.
I have function which returns a triangle representing a field of vision of a character drawn onto the canvas (triangle):

`Soldier.prototype.getVisionSAT = function(){
  var x = this.container.x, y = this.container.y;
  return new SAT.Polygon(
    new SAT.Vector(x,y),
    [
      new SAT.Vector(x,y),
      new SAT.Vector(x+40,y+130),
      new SAT.Vector(x-40,y+130)
    ]
  );
}`

I also have one to return the body of other characters:

`Soldier.prototype.getBodySAT = function(){
  return new SAT.Circle(new SAT.Vector(this.x,this.y), this.bodySize);
}`

All of these values passed to the SAT constructors are being used when drawing onto the canvas, so I can actully see when the triangle and circle overlap and when they don't.

The problem is that the testPolygonCircle function never seems to register a collision correctly. Sometimes it returns true when the characters are far away from one another. I checked the values passed into the testPolygonCircle function and they seem to be right... Can you see something I am doing obviously wrong? The ordering seems fine as well.

This is the response I get when the triangle collides with a circle. It seems like the response returns true even though the two objects don't seem to overlap:

![sat](https://cloud.githubusercontent.com/assets/10659431/15449478/24888eca-1f7f-11e6-9c3c-cb4581538663.png)

**Comment by jriecken** [comment]
It seems to work for me when I test it: take a look at this JSFiddle: https://jsfiddle.net/jkcvkx10/ - it tests a triangle against a circle that should not intersect and one that should intersect.

Are you sure what you are drawing is what is actually being used for calculations by SAT? Also, if you're reusing the `SAT.Response` object, make sure to call `.clear()` on it before doing another collision test.

**Comment by ppisecky** [comment]
I went three times through the code to make sure everything is fine and I think it is, but obviously somehting isnt. Essentially I have objects looking like this:

![soldier](https://cloud.githubusercontent.com/assets/10659431/15450820/0bf6961c-1fa8-11e6-9838-049d8ae20720.png)

And previously I was trying to test them against one another (meaning wheter circle of A is in triangle of B).

But now I tried even testing against the soldier himself (wheter his body is in his line of sight... you can see from the picture that it should be)
```
var vision = soldiers[i].getVisionSAT();
var body = soldiers[i].getBodySAT();
console.log(vision);
console.log(body);
console.log(SAT.testPolygonCircle(vision, body));
```

And this is what I get in the console:

![response](https://cloud.githubusercontent.com/assets/10659431/15450825/6ed68b98-1fa8-11e6-8c67-b160a0bcd702.png)

As you can see the the polygon and circle objects do seem to have vectors with the right coordinates- ones that intersect, but for some reason I get false. Am I missing something here completely?  I am stumped.

**Comment by ppisecky** [comment]
Again such a great library... makes life so much easier!

![great](https://cloud.githubusercontent.com/assets/10659431/15451888/1fb3dc50-1fda-11e6-9ae7-6b7becf245b0.png)

**Comment by jriecken** [comment]
Awesome! Yeah I missed seeing that in your original post - the `points` of a polygon are relative to the `pos`, not the global origin (this allows things like rotation to work easier)

Glad you got it working!
