### ISSUE TITLE
Rotating a polygon around it's center

### ISSUE THREAD

**Issue by scofield-ua** [jriecken/sat-js#34]
I have a problem. Is it possible to rotate polygon around it's center using Polygon class functions?

I'm trying to use `rotate` function, but it's return not what I expected.

Here is how my polygon looks by default:
![1](https://cloud.githubusercontent.com/assets/1827843/15547658/6d0f85b4-22ad-11e6-9c84-4bbdfd042691.png)

After `rotate(1)`:
![2](https://cloud.githubusercontent.com/assets/1827843/15547707/aa8e4bbe-22ad-11e6-8897-b34a949dedc3.png)

**Comment by jriecken** [comment]
How are you constructing the `Polygon` - do you have some example code?

The `rotate` method rotates using the `pos` of the `Polygon` as the origin of rotation (also it takes in the angle in radians, not degrees)

So if you use the `pos` as the center of the polygon and then define the `points` around/relative to that position it will rotate around that.

**Comment by scofield-ua** [comment]
> How are you constructing the Polygon - do you have some example code?

Sure, here is example code:

```
var P = SAT.Polygon; 
var V = SAT.Vector;
var points = [];

var angle = 0.05;
var r = 64;
while (angle < 2 * Math.PI / 2) {
    var x = r * -Math.cos(angle);
    var y = r * -Math.sin(angle);

    points.push(new V(x, y));

    angle += 0.5;
}

var polygon = new P(new V(100, 100), points);
```

**Comment by jriecken** [comment]
Hm, that seems to work for me - take a look at this JSFiddle: https://jsfiddle.net/1d67zsaw/

I copied your code, drew the polygon, rotated it, and drew it again - it rotates around the center of the half-circle.

**Comment by scofield-ua** [comment]
Yeah. Thanks man. Seems like odd behavior from engine polygon draw method.

Nice library.
