### ISSUE TITLE
Distance between two vectors

### ISSUE THREAD

**Issue by scofield-ua** [jriecken/sat-js#36]
Hello, I have a question. Is it possible to find distance between two vectors using SAT.Vector class?

**Comment by jriecken** [comment]
You should just be able to subtract one from the other - that should give you a Vector whose magnitude is the distance between them

Example:

Given a vector A `(0,1)` and B `(1,0)`, subtracting A from B gives vector C `(1, -1)` , which is a vector that goes from B to A if you start at B (the magnitude of that vector is the distance between them)

**Comment by scofield-ua** [comment]
Yes it's right.

Anyway, I made [a function](https://github.com/scofield-ua/sat-js/blob/94c60270c830f11a932693a651e1c998e95ddb05/SAT.js#L250) to determine distance which return "some" number. But seems like this don't fit the library and make same thing like `len` function.
