### ISSUE TITLE
Contact point

### ISSUE THREAD

**Issue by lcnvdl** [jriecken/sat-js#37]
Hi! Is there a way to get the contact point between two polygons?

Thank you

**Comment by jriecken** [comment]
Sadly there's nothing in the lib that will give you this. There could be many (or infinite) collision points depending on how the polygons are oriented (e.g. think of two squares sitting on top of each other - they contact along the entire line segment of the top of the one box and the bottom of the other)

You might be able to individually test each edge of the polygon to see which one(s) collide and then use the overlap vector in the `Result` to determine the exact point - but i'm not 100% sure that would work in all cases.

**Comment by Nashorn** [comment]
I think this issue should open back up, its important for integrating physics
