### ISSUE TITLE
Get what half of what edge polygon collids to.

### ISSUE THREAD

**Issue by SzAmmi** [jriecken/sat-js#38]
Here's the polygon:
```javascript
new SAT.Box(new SAT.Vector(0, 0), 69, 40).toPolygon().translate(-34.5, -20)
```
Is it possible to detect what half of what edge (1 or 3) another polygon collids to?
![untitled](https://cloud.githubusercontent.com/assets/9989553/17106572/202d9cf4-528c-11e6-873e-40a5a82fd1e5.png)
**The polygons may be rotated.**

**Comment by jriecken** [comment]
I don't think there's a simple way to get this - This lib only tells you if two items collide and what the shortest vector to move either of them to not make them collide anymore.

This is somewhat similar to #37 

You might be able to use the overlap vector returned in the collision response to determine which edge the colliding polygon was closest to, but I'm not sure you're going to be able to get anything more than that. The colliding polygon could be on both halves of the edges.

**Comment by Nashorn** [comment]
what about taking the mid-point of an edge?
