### ISSUE TITLE
maybe a bug ?

### ISSUE THREAD

**Issue by nxgraphics** [jriecken/sat-js#40]
i was trying to set 2 boxes next to each other, but it was giving me indication that they were collidiing as they werent,
so i change the code: 
 if (rangeA[0] > rangeB[1] || rangeB[0] > rangeA[1]) {  // line 622 of sat.js 

to :

if (rangeA[0] >= rangeB[1] || rangeB[0] >= rangeA[1]) { 

and it fixed it

**Comment by jriecken** [comment]
Is it when two boxes are directly touching each other?

I guess it could be argued either way, but the current expected behaviour is that if two objects are directly touching each other, they are colliding.

**Comment by nxgraphics** [comment]
hi jriecken,
yes your right it could be argued :) well lets say we put 2 boxes on a floor, next to each other, in the concept they are not colliding, but 'touching' since no force is applied to them, the flag .collide should not be triggered.
in the actual implementation, i cant put them close to each other, except if i put a gap on 1 pixel...
i think the test collision should occur if they are intersecting,
well all depends if they are touching with force and touching with no force at current T time
