### ISSUE TITLE
testCirclePolygon result error

### ISSUE THREAD

**Issue by zsytssk** [jriecken/sat-js#44]
I'm write a game, use sat.js detect shape collision; I find a bug , but maybe is my misunderstand of api;
here is my demo code

```javascript
var circle = new SAT.Circle(new SAT.Vector(444,571), 67);  
var polygon = new SAT.Polygon(new SAT.Vector(750,294), [  
  new SAT.Vector(1,-70),  
  new SAT.Vector(-60,46),  
  new SAT.Vector(60,46)  
]);  
polygon.setAngle(2.7173982456860264);
var response = new SAT.Response();  
var collided = SAT.testCirclePolygon(circle, polygon, response)
console.log(collided);
```
here is my demo page clip
![tim 20170320145210](https://cloud.githubusercontent.com/assets/2304648/24090693/8ef40a72-0d7d-11e7-99a1-96a46590d2fa.png)

the red fish(triangle shape) is collisioned with the net(circle shape); you can see some of them should never be collisioned; the demo code is I use  red border box mark net and fish;

**Comment by jriecken** [comment]
I think you're specifying the points of the polygon in the wrong order.

From the docs:

> Note: The points are counter-clockwise with respect to the coordinate system. If you directly draw the points on a screen that has the origin at the top-left corner it will appear visually that the points are being specified clockwise. This is just because of the inversion of the Y-axis when being displayed.

If you create the polygon with the points like this, you get the expected result:

```javascript
var polygon = new SAT.Polygon(new SAT.Vector(750,294), [  
  new SAT.Vector(1,-70),  
  new SAT.Vector(60,46),  
  new SAT.Vector(-60,46)  
]);  
```

**Comment by zsytssk** [comment]
thanks
