### ISSUE TITLE
Importing via ES6?

### ISSUE THREAD

**Issue by timoman7** [jriecken/sat-js#46]
Would it be possible to import SAT as a class via ES6? Would it need to be rebuilt from the ground up, or is there a method to convert it to a class?

**Comment by jriecken** [comment]
The main `SAT` namespace is just a javascript object. I think you should be able to treat the `Vector` / `Polygon` / `Circle` / `Box` / `Response` inside it as classes as-is.

Are you running into any problems?

**Comment by timoman7** [comment]
To expand on this, I'm using the import/export in ES6, and since I just started ES6 yesterday after 5 years of using type='text/javascript', I'm not too knowledgeable when it comes to that syntax. Do you know if, in SAT.js, I would use `export default function SAT(){ ... }`?

**Comment by jcb121** [comment]
If you're using webpack, id you try `import * as SAT from './sat.js'`? this is how PIXI.js handles being imported even though it's attached to the global namespace.

Also, I'd love it if you made it an NPM package! 💯

**Comment by jriecken** [comment]
It already is an NPM package 😄 - https://www.npmjs.com/package/sat
