### ISSUE TITLE
Move A Polygon?

### ISSUE THREAD

**Issue by gididaf** [jriecken/sat-js#49]
I don't get it.
How can I simply move a polygon?
I tried to change the POS propery - nothing happened (The Points or CalcPoints not updating).
I tried to use the Translate method - it's working but then the collision detection not working.
What am I doing wrong? How can I just move a polygon and keep collision detection working?

**Comment by jriecken** [comment]
You should just have to change the `pos` to move it. The `points` of a polygon are all relative to the `pos` (i.e. if you're drawing it on screen you have to add `pos` to each of the `calcPoints`).

If that doesn't help, can you provide a code example of how it's not working? Thanks!

**Comment by gididaf** [comment]
ok now I feel stupid :)
Thank you very much!
Awesome work btw
