### ISSUE TITLE
Gets the center of the polygon?

### ISSUE THREAD

**Issue by gididaf** [jriecken/sat-js#50]
Currently, to rotate the polygon around its center, we should give the exact X and Y coordinates to the pos vector of the polygon, but it's seems there is no way to calculate the center of the polygon.

**Comment by jriecken** [comment]
The correct way to do this (since the polygons in SAT must be convex/non-intersecting) would be to calculate the [Centroid](https://en.wikipedia.org/wiki/Centroid#Centroid_of_a_polygon)

I can add a `centroid` method to `Polygon` when I get some time (or a Pull Request would be great!)

**Comment by jriecken** [comment]
I've added this (and released version 0.7.0 that has it in it).

**Comment by gididaf** [comment]
Wow! Thank you very much for that!
