### ISSUE TITLE
Request for element collision along with stroke

### ISSUE THREAD

**Issue by gsudhakarb** [jriecken/sat-js#51]
Hi,
If possible to detect the collision with stroke(for circle,polygon etc). If the stroke-width set as 4 pixels for polygon than the 4 pixels also calculate for the hit region. Thank you.

**Comment by jriecken** [comment]
You mean when you draw the shapes? I'm not sure this is something that should be in this lib as `sat-js` is mainly focused on non-visual collision shapes, which are not necessarily the same as what would be drawn (they can be though).

Some things you could try:
- Only drawing the stroke on the inside of the shape. If you're using `canvas` you can do this by clipping to the shape before stroking it (and doubling the stroke width as it will only draw the inside part). Example: https://jsfiddle.net/t4dn86os/6/
- Shrinking the shape by half the stroke width (this may be complicated though)
