### ISSUE TITLE
converting SAT.Box to polygon (using toPolygon()) creates a polygon whose centroid never changes (top-left point always at 0,0)

### ISSUE THREAD

**Issue by keshav2010** [jriecken/sat-js#70]
```
 Box.prototype['toPolygon'] = Box.prototype.toPolygon = function () {
    var pos = this['pos'];
    var w = this['w'];
    var h = this['h'];
    return new Polygon(new Vector(pos['x'], pos['y']), [
      new Vector(), new Vector(w, 0),
      new Vector(w, h), new Vector(0, h)
    ]);
  };
```

it seems that translation is not applied to the polygon here for SAT.Box,

even though we're creating polygon out of a SAT.Box that has a position defined, 
but still it will always have its top-left vertex positioned at 0,0 and thus causes an issue when calculating centroid because centroid value never changes and is calculated by assuming that polygon is positioned at (0,0).

Suggested Change:

```
 Box.prototype['toPolygon'] = Box.prototype.toPolygon = function () {
    var pos = this['pos'];
    var w = this['w'];
    var h = this['h'];
    return new Polygon(new Vector(pos['x'], pos['y']), [
      new Vector(), new Vector(w, 0),
      new Vector(w, h), new Vector(0, h)
    ]).translate(pos.x, pos.y);
  };
```

**Comment by jriecken** [comment]
All points (including the calculated centroid) are relative to the polygon's `pos`. If you want the absolute coordinates you need to add the `pos` to each point.

From the readme for `SAT.Polygon`:

> `pos` - The position of the polygon (all points are relative to this).
